import { escapeHtml } from "./escape.js";
export function pairPage({ code = "", authenticated = false, approved = false, expired = false } = {}) {
  const title = expired ? "연결 시간이 지났습니다." : approved ? "샵 연결을 승인했습니다." : "샵 연결";
  const content = expired ? '<p>스위치에서 새 QR을 확인하고 다시 스캔합니다.</p>'
    : approved ? '<p>스위치가 자동으로 샵에 연결합니다. 이 창을 닫아도 됩니다.</p>'
    : `<p>스위치에 표시된 기기 코드와 같은지 확인합니다.</p><strong class="device-code">${escapeHtml(code)}</strong>
${authenticated ? '<form id="approve"><label for="label">기기 이름 <span>(선택)</span></label><input id="label" maxlength="64" placeholder="Nintendo Switch" autocomplete="off"><button type="submit">이 기기를 연결합니다</button></form>'
    : '<form id="verify"><label for="code">관리자 인증 앱의 6자리 코드</label><input id="code" inputmode="numeric" pattern="[0-9]{6}" autocomplete="one-time-code" maxlength="6" required autofocus><button type="submit">인증합니다</button></form><p class="hint">샵 관리자만 연결을 승인할 수 있습니다.</p>'}
<p id="error" role="alert"></p>`;
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>CookingFoil · 샵 연결</title>
<link rel="stylesheet" href="/assets/fonts.css"><style>:root{color-scheme:light;font-family:'IBM Plex Sans KR',system-ui,sans-serif;color:#16161A;background:#F2F1EE}*{box-sizing:border-box}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:24px}.card{background:#fff;border:1px solid #E2E0DA;border-radius:20px;padding:32px;width:min(100%,440px)}.brand{display:flex;align-items:center;gap:12px;font-size:22px;font-weight:700;letter-spacing:.04em;margin:0 0 28px}.brand b{background:#FFC23D;border-radius:8px;padding:7px 10px;margin-right:8px}h1{font-size:28px;margin:0 0 14px}p{font-size:17px;line-height:1.6;color:#55555E;margin:0 0 20px;word-break:keep-all}.device-code{display:block;font:700 30px monospace;letter-spacing:3px;padding:18px;text-align:center;background:#F2F1EE;border-radius:12px;margin:24px 0}label{display:block;font-size:17px;margin-bottom:10px}label span{color:#55555E}input{font:inherit;font-size:20px;width:100%;border:1px solid #E2E0DA;border-radius:10px;padding:14px;background:#fff;color:#16161A}#code{text-align:center;letter-spacing:5px}button{font:inherit;font-weight:700;font-size:18px;width:100%;border:0;border-radius:10px;padding:16px;background:#FFC23D;color:#16161A;margin:18px 0;cursor:pointer}button:disabled{opacity:.6;cursor:wait}input:focus-visible,button:focus-visible{outline:4px solid #0AB4E8;outline-offset:3px}.hint{margin:0;font-size:17px}#error{color:#982929;margin:12px 0 0;min-height:0}@media(max-width:420px){body{padding:16px}.card{padding:24px}}</style></head><body><main class="card"><div class="brand"><span aria-hidden="true" style="font-size:34px;line-height:1">🧈</span>CookingFoil</div><h1>${title}</h1>${content}</main>
<script>
const verify=document.getElementById('verify'),approve=document.getElementById('approve'),error=document.getElementById('error');
async function submit(form,url,body){const button=form.querySelector('button');button.disabled=true;error.textContent='';try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(response.ok){location.reload();return;}error.textContent=response.status===410?'연결 시간이 지났습니다. 스위치의 새 QR을 스캔합니다.':response.status===401?'관리자 인증을 확인합니다.':response.status===409?'이미 처리된 요청입니다. 스위치에서 연결을 확인합니다.':'연결을 처리하지 못했습니다. 다시 시도합니다.';}catch{error.textContent='서버에 연결하지 못했습니다. 다시 시도합니다.';}finally{button.disabled=false;}}
if(verify)verify.addEventListener('submit',e=>{e.preventDefault();submit(verify,'/admin/verify',{code:document.getElementById('code').value});});
if(approve)approve.addEventListener('submit',e=>{e.preventDefault();submit(approve,'/admin/api/pair/'+location.pathname.split('/').pop()+'/approve',{label:document.getElementById('label').value});});
</script></body></html>`;
}
